version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint
    versions:
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: webpack
    versions:
    - 5.19.0
    - 5.21.2
    - 5.24.2
    - 5.25.1
    - 5.27.1
    - 5.31.2
  - dependency-name: husky
    versions:
    - 5.1.0
    - 5.1.2
