version: 2.1

orbs:
  node: circleci/node@7.1.0

jobs:
  build:
    docker:
      - image: cimg/node:22.16.0
    steps:
      - checkout

      - restore_cache:
          name: Restore pnpm Package Cache
          keys:
            - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Configure pnpm package manager
          command: |
            pnpm config set store-dir .pnpm-store

      - run:
          name: Install Dependencies
          command: |
            pnpm install
      - save_cache:
          name: Save pnpm Package Cache
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - .pnpm-store

      - run:
          name: Run linter
          command: |
            pnpm lint

      - run:
          name: Run test coverage
          command: |
            pnpm test:coverage

workflows:
  build-workflow:
    jobs:
      - build
