version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  build:
    docker:
      - image: cimg/node:16.19.0
    steps:
      - checkout
      - node/install-packages
      - run:
          name: 'Run coverage'
          command: 'npm run coverage'

  # matrix-tests:
  #   jobs:
  #     - node/test:
  #         matrix:
  #           parameters:
  #             version:
  #               - 19.5.0
  #               - 18.12.0
  #               - 16.13.0
  #               - 14.21.2

workflows:
  build-workflow:
    jobs:
      - build
      # - matrix-tests
