version: 2.1

orbs:
  node: circleci/node@5.2.0

jobs:
  build:
    docker:
      - image: cimg/node:20.16.0
    steps:
      - checkout
      - node/install-packages
      - run:
          name: 'Run coverage'
          command: 'npm run coverage'

workflows:
  build-workflow:
    jobs:
      - build
